# Generated by Django 4.2.23 on 2025-11-09 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_category',
            field=models.CharField(blank=True, choices=[('software', 'Software Development'), ('ecommerce', 'E-commerce'), ('consulting', 'Consulting'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_email',
            field=models.EmailField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='date_of_incorporation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='mono_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='monthly_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='profit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pulse_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
