# Generated by Django 5.2.8 on 2025-11-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0003_auto_20251109_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
