# Generated by Django 5.2.8 on 2025-11-13 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
        ('lender', '0001_initial'),
        ('sme', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_received', to='lender.lenderprofile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sme_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='sme.businessprofile'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_account', to='escrow.loanapplication'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='escrow.loanapplication'),
        ),
        migrations.AddField(
            model_name='loannegotiation',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='escrow.loanapplication'),
        ),
        migrations.AddField(
            model_name='loannegotiation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='escrow.loanapplication'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='escrow_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='escrow.escrowaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='escrow.loanapplication'),
        ),
        migrations.AlterUniqueTogether(
            name='repaymentschedule',
            unique_together={('loan_application', 'installment_number')},
        ),
    ]
