# Generated by Django 5.2.8 on 2025-11-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
        ('lender', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='lender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_received', to='lender.lenderprofile'),
        ),
    ]
