# Generated by Django 5.2.8 on 2025-11-13 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sme', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_type', models.CharField(choices=[('bank', 'Bank'), ('microfinance', 'Microfinance Bank'), ('investor', 'Private Investor'), ('venture', 'Venture Capital'), ('other', 'Other')], max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('years_in_operation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('preferred_industries', models.JSONField(default=list)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_appetite', models.IntegerField(help_text='1 (Low Risk) to 10 (High Risk)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('office_address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_documents', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lender_profiles',
            },
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_filters', to='lender.lenderprofile')),
            ],
            options={
                'db_table': 'lender_search_filters',
            },
        ),
        migrations.CreateModel(
            name='SMEInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('viewed', 'Viewed'), ('interested', 'Interested'), ('contacted', 'Contacted'), ('rejected', 'Rejected'), ('funded', 'Funded')], default='viewed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='lender.lenderprofile')),
                ('sme_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_interests', to='sme.businessprofile')),
            ],
            options={
                'db_table': 'lender_sme_interests',
                'unique_together': {('lender', 'sme_business')},
            },
        ),
    ]
