# Generated by Django 5.2.8 on 2025-11-09 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lender', '0001_initial'),
        ('sme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchfilter',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_filters', to='lender.lenderprofile'),
        ),
        migrations.AddField(
            model_name='smeinterest',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='lender.lenderprofile'),
        ),
        migrations.AddField(
            model_name='smeinterest',
            name='sme_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_interests', to='sme.businessprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='smeinterest',
            unique_together={('lender', 'sme_business')},
        ),
    ]
